### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by stevenvachon** [Xotic750/has-to-string-tag-x#2]
I'm getting daily reports from [greenkeeper](https://greenkeeper.io) to update my projects with your auto builds. It's really annoying.

**Comment by Xotic750** [comment]
I'm sorry that you feel annoyed, however after nearly 2 years of not updating and finding myself with 180 projects that depend on one another, I am trying my best to automate a great deal of this maintenance work. I continue to improve my automation script so that it doesn't happen too often, however it's far from perfect at the moment. Things will settle down shortly. Thanks for your patience.

**Comment by stevenvachon** [comment]
Maybe set the auto stuff to major version changes only. I don't think anything less is necessary when using server ranges.

**Comment by stevenvachon** [comment]
Also, bundled files are not necessary in the modern web dev world where everyone is using or will be using a bundler.

**Comment by Xotic750** [comment]
Unfortunately I still deal with projects that are 8-10 years old and don't have a build/packaging system, and that what I get paid for. I will work things out as soon as I can.

**Comment by Xotic750** [comment]
Ok, I have made changes to the build script that should address this.
